### ISSUE TITLE
FHIR RDF?

### ISSUE THREAD

**Issue by dwaite** [mattrglobal/vaccination-certificate-vocab#1]
Is there a particular reason against the FHIR RDF/JSON-LD vocabulary?

**Comment by tplooker** [comment]
@dwaite no, happy to take any input on evolving this vocab as stated in the readme it is merely a starting point and was primarily based around [this document that was published recently](https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf)

**Comment by tplooker** [comment]
Could you supply relevant links for review and suggested points of intersection?

**Comment by tplooker** [comment]
Hi @dwaite this item has now been adopted by the CCG would you mind re-opening your issue [here](https://github.com/w3c-ccg/vaccination-vocab)
