### ISSUE TITLE
Defining in terms of schema.org / combining efforts?

### ISSUE THREAD

**Issue by dpjanes** [mattrglobal/vaccination-certificate-vocab#2]
Note the C4 effort here:
https://cccc4.ca/

Technical spec:
https://cccc4.ca/l/vcprop

Example tools:
https://passport.consensas.com/

Example data:
https://passport.consensas.com/did:example:HXCFWCSUUA.json

**Comment by tplooker** [comment]
Hi @dpjanes this item has now been adopted by the CCG would you mind re-opening your issue [here](https://github.com/w3c-ccg/vaccination-vocab)
